### ISSUE TITLE
getSendConfig returns error

### ISSUE THREAD

**Issue by jiqing112** [Mikubill/cowtransfer-uploader#1]
```
[root@vultrguest ~]# ./cowtransfer-uploader cowtransfer-uploader 

getSendConfig returns error: Post "https://cowtransfer.com/transfer/preparesend": context deadline exceeded (Client.Timeout exceeded while awaiting headers), onfile: cowtransfer-uploaderpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x734465]

goroutine 1 [running]:
main.upload.func1(0x7ffc04e81797, 0x14, 0x871500, 0xc000055380, 0x0, 0x0, 0x4cc38f, 0xc000055380)
	/github/workspace/uploader.go:44 +0x165
path/filepath.walk(0x7ffc04e81797, 0x14, 0x871500, 0xc000055380, 0x7fff30, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:360 +0x425
path/filepath.Walk(0x7ffc04e81797, 0x14, 0x7fff30, 0xd0, 0xd0)
	/usr/local/go/src/path/filepath/path.go:406 +0xff
main.upload(0xc000040d80, 0x1, 0x1)
	/github/workspace/uploader.go:36 +0x74f
main.main()
	/github/workspace/main.go:78 +0x12d

```

**Comment by jiqing112** [comment]
通过 curl -sL https://git.io/cowtransfer | sh 下载的可执行文件。centos8，没有go环境

**Comment by Mikubill** [comment]
接口超时了，多试几次（

Note: https://cowtransfer.com/transfer/preparesend 在国外使用貌似不太稳定，需要提高此类接口的超时时间。

**Comment by Mikubill** [comment]
尝试着改进了一下自动重试，可以用`curl -L https://git.io/cowtransfer  | sh`更新版本，然后用较小的超时时间（如`./cowtransfer-uploader -t 3`）测试一下

**Comment by Mikubill** [comment]
closed.

如果仍然有此问题可以重新打开issue.
