### ISSUE TITLE
小文件过多会报错

### ISSUE THREAD

**Issue by pongfcnkl** [Mikubill/cowtransfer-uploader#19]
报错如下
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x73b870]

goroutine 1 [running]:
main.getUploadConfig(0x87c4a0, 0xc0001f6150, 0xc00050c100, 0xc0001f6150, 0x0, 0x0)
        /github/workspace/uploader.go:440 +0x420
main._upload(0xc0000c2040, 0x32, 0xc00050c100, 0xc0000c2040, 0x32)
        /github/workspace/uploader.go:138 +0x1d8
main.upload.func3(0xc0000c2040, 0x32, 0x87c4a0, 0xc0001f6000, 0x0, 0x0, 0x32, 0x0)
        /github/workspace/uploader.go:109 +0x189
path/filepath.walk(0xc0000c2040, 0x32, 0x87c4a0, 0xc0001f6000, 0xc0000cfcc8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:360 +0x42c
path/filepath.walk(0xc0004aa2c0, 0x1e, 0x87c4a0, 0xc000120230, 0xc0000cfcc8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:384 +0x306
path/filepath.walk(0xc00000b9a0, 0x16, 0x87c4a0, 0xc0001f62a0, 0xc0000cfcc8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:384 +0x306
path/filepath.walk(0xc0003f2e40, 0xf, 0x87c4a0, 0xc0001f61c0, 0xc0000cfcc8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:384 +0x306
path/filepath.walk(0xc0000100e0, 0x3, 0x87c4a0, 0xc0001f62a0, 0xc0000cfcc8, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:384 +0x306
path/filepath.Walk(0xc0000100e0, 0x3, 0xc000069cc8, 0x10, 0xc000069d08)
        /usr/local/go/src/path/filepath/path.go:406 +0x106
main.upload(0xc00002ecd0, 0x1, 0x1)
        /github/workspace/uploader.go:101 +0x322
main.main()
        /github/workspace/main.go:78 +0x339
```

**Comment by Mikubill** [comment]
看起来像是无法获得上传参数。文件过多的时候可以试着用合并上传 （-s 参数）较少API请求

**Comment by pongfcnkl** [comment]
> 
> 
> 看起来像是无法获得上传参数。文件过多的时候可以试着用合并上传 （-s 参数）较少API请求

加上-s也是一样报错
